# LLM Routing Configuration for AIOSv3
# This file defines how tasks are routed to different LLM providers

# Provider configurations
providers:
  claude:
    enabled: true
    priority: 1  # Higher priority = preferred
    capabilities:
      - complex_reasoning
      - code_generation
      - analysis
      - creative_writing
    constraints:
      max_cost_per_request: 1.0
      rate_limit_per_minute: 100
    
  openai:
    enabled: true
    priority: 2
    capabilities:
      - code_generation
      - general_purpose
      - function_calling
    constraints:
      max_cost_per_request: 0.5
      rate_limit_per_minute: 100
    
  ollama:
    enabled: true
    priority: 3  # Highest priority for cost optimization
    capabilities:
      - simple_tasks
      - code_completion
      - text_generation
    constraints:
      max_response_time_ms: 10000
      min_available_memory_gb: 4

# Task routing rules
routing_rules:
  # Complex tasks requiring high intelligence
  - task_types:
      - system_design
      - architecture_review
      - tech_decision
    complexity_range: [8, 10]
    preferred_providers: ["claude"]
    fallback_providers: ["openai"]
    
  # Code generation tasks
  - task_types:
      - code_generation
      - code_review
      - bug_fix
      - refactoring
    complexity_range: [5, 10]
    preferred_providers: ["claude", "openai"]
    fallback_providers: ["ollama"]
    
  # Testing and documentation
  - task_types:
      - testing
      - documentation
    complexity_range: [3, 7]
    preferred_providers: ["openai", "ollama"]
    fallback_providers: ["claude"]
    
  # Simple text generation
  - task_types:
      - text_generation
      - status_report
    complexity_range: [1, 5]
    preferred_providers: ["ollama"]
    fallback_providers: ["openai", "claude"]
    
  # Analysis tasks
  - task_types:
      - performance_analysis
      - requirements_analysis
      - risk_assessment
    complexity_range: [6, 9]
    preferred_providers: ["claude"]
    fallback_providers: ["openai"]

# Cost optimization settings
cost_optimization:
  # Target percentage of requests to route to local models
  local_model_target_percentage: 70
  
  # Maximum acceptable cost per day
  daily_budget_usd: 50.0
  
  # Cost thresholds for automatic optimization
  thresholds:
    high_cost_alert: 0.50  # Alert if single request > $0.50
    force_local_above: 0.20  # Force local model if estimated cost > $0.20

# Model preferences by agent type
agent_model_preferences:
  cto_agent:
    preferred_models:
      - claude-3-5-sonnet-20241022
      - gpt-4-turbo
    min_performance_tier: 4
    
  backend_agent:
    preferred_models:
      - claude-3-5-sonnet-20241022
      - gpt-4-turbo
      - codellama:34b
    min_performance_tier: 3
    
  frontend_agent:
    preferred_models:
      - gpt-4-turbo
      - claude-3-5-sonnet-20241022
      - llama3:8b
    min_performance_tier: 3
    
  qa_agent:
    preferred_models:
      - gpt-3.5-turbo
      - claude-3-haiku-20240307
      - llama3:8b
    min_performance_tier: 3
    
  devops_agent:
    preferred_models:
      - gpt-4-turbo
      - claude-3-5-sonnet-20241022
      - mixtral:8x7b
    min_performance_tier: 4

# Performance requirements
performance_requirements:
  # Maximum acceptable response times by task complexity
  response_time_targets:
    simple: 2000  # 2 seconds
    medium: 5000  # 5 seconds
    complex: 30000  # 30 seconds
    
  # Availability requirements
  min_availability: 0.95
  
  # Quality thresholds
  min_success_rate: 0.90

# Privacy and compliance
privacy_settings:
  # Force local models for these data types
  privacy_sensitive_patterns:
    - "password"
    - "api_key"
    - "secret"
    - "credential"
    - "ssn"
    - "credit_card"
    
  # Require local processing for these agent operations
  local_only_operations:
    - "credential_management"
    - "secret_rotation"
    - "compliance_audit"